### ISSUE TITLE
Print the Polynomial

### ISSUE THREAD

**Issue by suhelsayyad2006** [dwu4/fhe-si#1]
Hello

I wish to work the test programs with my own data. For that I need to understand how existing Plain Text data is organised in form of ZZ_pX. 
Please help me understand how can I model this Test_AddMul so as to run it on my data

**Comment by dwu4** [comment]
You can use the methods provided by the `Plaintext` class to embed scalar elements in the slots of the plaintext space. See also `Test_Statistics.cpp` and `Test_Regression.cpp` for concrete examples of packing values into a single plaintext vector and performing homomorphic operations on the vectors.

**Comment by suhelsayyad2006** [comment]
Where can I find datafile for Test_Statistics.cpp
Can this library be used to perform neural network learning on encrypted data
